### PR TITLE
Aic8800

### PR DESCRIPTION
**Pull request by 0x754C**

### CODE REVIEW

**Comment by nekorouter** [comment]
Debug message is still on and output tons of log into dmesg

**Comment by nekorouter** [comment]
Bluetooth is not working.
```
debian@lpi4a:~$ sudo dmesg | grep RF
[sudo] password for debian: 
[    0.000000] SBI v0.2 RFENCE extension detected
[    3.717124] Bluetooth: RFCOMM TTY layer initialized
[    3.722108] Bluetooth: RFCOMM socket layer initialized
[    3.727343] Bluetooth: RFCOMM ver 1.11
[    3.756950] [WLAN_RFKILL]: Enter rfkill_wlan_init
[    3.762220] [WLAN_RFKILL]: Enter rfkill_wlan_probe
[    3.767062] [WLAN_RFKILL]: can't find rockchip,grf property
[    3.772666] [WLAN_RFKILL]: wlan_platdata_parse_dt: wifi_chip_type = rtl8723ds
[    3.779830] [WLAN_RFKILL]: wlan_platdata_parse_dt: wifi power will enabled while kernel starting and keep on.
[    3.789832] [WLAN_RFKILL]: wlan_platdata_parse_dt: wifi power controled by gpio.
[    3.797353] [WLAN_RFKILL]: wlan_platdata_parse_dt: The ref_wifi_clk not found !
[    3.804764] [WLAN_RFKILL]: rfkill_wlan_probe: init gpio
[    3.815522] [WLAN_RFKILL]: rockchip_wifi_power: 1
[    3.820295] [BT_RFKILL]: rfkill_get_bt_power_state: rfkill-bt driver has not Successful initialized
[    3.834837] [WLAN_RFKILL]: wifi turn on power. -1
[    3.844100] [WLAN_RFKILL]: Exit rfkill_wlan_probe
[    3.848983] [BT_RFKILL]: Enter rfkill_rk_init
[    3.853814] [BT_RFKILL]: bluetooth_platdata_parse_dt: uart_rts_gpios is no-in-use.
[    3.861489] [BT_RFKILL]: bluetooth_platdata_parse_dt: clk_get failed!!!.
[    3.868408] [BT_RFKILL]: bt_default device registered.
[   13.419767] AICWFDBG(LOGTRACE)       rwnx_send_msg (106)MM_SET_RF_CALIB_CFM reqcfm:1 in_irq:0 in_softirq:0 in_atomic:0
[   13.663158] [BT_RFKILL]: bt turn on power
[   49.624427] [BT_RFKILL]: bt shut off power
[   53.711082] [BT_RFKILL]: bt turn on power
```

**Review by nekorouter — APPROVED** [review]
tested by nekorouter (BT problem will make a new issue)

**Comment by newluhux** [comment]
before execute hciattach, you may be need remove old rtk-hciattach service

**Comment by newluhux** [comment]
and hciattach must execute after `insmod aic8800_fdrv`, because bluetooth mcu firmware is load from sdio.

**Comment by 0x754C** [comment]
userspace need execute: hciattach ttyS4 any 1500000

**Pull request merged**
