### PR TITLE
feat: remove compression for riscv Image

### PR DESCRIPTION
**Pull request by RevySR**

### CODE REVIEW

**Comment by xmzzz** [comment]
Is the purpose of this patch to obtain an uncompressed kernel after `make install` ?
If that's the case, simply change `make zinstall` to `make install`. This will achieve the goal.
I have verified locally and obtained the following results:

On this commit ID: 576468ca7e36

```
$ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- revyos_defconfig
$ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- -j32
$ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- INSTALL_PATH=$HOME/revyOS/rootfs/boot install
$ file $HOME/revyOS/rootfs/boot/vmlinuz-5.10.113-g576468ca7e36 
vmlinuz-5.10.113-g576468ca7e36: MS-DOS executable PE32+ executable (EFI application) RISC-V 64-bit (stripped to external PDB), for MS Windows
```

On the previous commit ID: 8cf226ab7154
```
$ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- revyos_defconfig
$ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- -j32
$ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- INSTALL_PATH=$HOME/revyOS/rootfs/boot install
$ file $HOME/revyOS/rootfs/boot/vmlinuz-5.10.113-g8cf226ab7154
vmlinuz-5.10.113-g8cf226ab7154: MS-DOS executable PE32+ executable (EFI application) RISC-V 64-bit (stripped to external PDB), for MS Windows
```

The two files are the same.

**Comment by RevySR** [comment]
> Is the purpose of this patch to obtain an uncompressed kernel after `make install` ? If that's the case, simply change `make zinstall` to `make install`. This will achieve the goal. I have verified locally and obtained the following results:
> 
> On this commit ID: [576468c](https://github.com/revyos/thead-kernel/commit/576468ca7e368ed595e346b7a9767ea8e62fa2b4)
> 
> ```
> $ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- revyos_defconfig
> $ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- -j32
> $ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- INSTALL_PATH=$HOME/revyOS/rootfs/boot install
> $ file $HOME/revyOS/rootfs/boot/vmlinuz-5.10.113-g576468ca7e36 
> vmlinuz-5.10.113-g576468ca7e36: MS-DOS executable PE32+ executable (EFI application) RISC-V 64-bit (stripped to external PDB), for MS Windows
> ```
> 
> On the previous commit ID: [8cf226a](https://github.com/revyos/thead-kernel/commit/8cf226ab71549e0e07ba8fff38950bd45380b901)
> 
> ```
> $ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- revyos_defconfig
> $ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- -j32
> $ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- INSTALL_PATH=$HOME/revyOS/rootfs/boot install
> $ file $HOME/revyOS/rootfs/boot/vmlinuz-5.10.113-g8cf226ab7154
> vmlinuz-5.10.113-g8cf226ab7154: MS-DOS executable PE32+ executable (EFI application) RISC-V 64-bit (stripped to external PDB), for MS Windows
> ```
> 
> The two files are the same.

The commit is for future packaging deb preparation.

https://github.com/revyos/thead-kernel/blob/8cf226ab71549e0e07ba8fff38950bd45380b901/scripts/package/builddeb#L150

`$MAKE -s -f $srctree/Makefile image_name` equal to `KBUILD_IMAGE`

`KBUILD_IMAGE` determines the kernel copied to the deb package

**Comment by RevySR** [comment]
> Is the purpose of this patch to obtain an uncompressed kernel after `make install` ? If that's the case, simply change `make zinstall` to `make install`. This will achieve the goal. I have verified locally and obtained the following results:
> 
> On this commit ID: [576468c](https://github.com/revyos/thead-kernel/commit/576468ca7e368ed595e346b7a9767ea8e62fa2b4)
> 
> ```
> $ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- revyos_defconfig
> $ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- -j32
> $ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- INSTALL_PATH=$HOME/revyOS/rootfs/boot install
> $ file $HOME/revyOS/rootfs/boot/vmlinuz-5.10.113-g576468ca7e36 
> vmlinuz-5.10.113-g576468ca7e36: MS-DOS executable PE32+ executable (EFI application) RISC-V 64-bit (stripped to external PDB), for MS Windows
> ```
> 
> On the previous commit ID: [8cf226a](https://github.com/revyos/thead-kernel/commit/8cf226ab71549e0e07ba8fff38950bd45380b901)
> 
> ```
> $ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- revyos_defconfig
> $ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- -j32
> $ make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- INSTALL_PATH=$HOME/revyOS/rootfs/boot install
> $ file $HOME/revyOS/rootfs/boot/vmlinuz-5.10.113-g8cf226ab7154
> vmlinuz-5.10.113-g8cf226ab7154: MS-DOS executable PE32+ executable (EFI application) RISC-V 64-bit (stripped to external PDB), for MS Windows
> ```
> 
> The two files are the same.

https://github.com/revyos/thead-kernel/blob/8cf226ab71549e0e07ba8fff38950bd45380b901/scripts/package/builddeb#L150

`$MAKE -s -f $srctree/Makefile image_name` equal to `KBUILD_IMAGE`

`KBUILD_IMAGE` determines the kernel copied to the deb package

**Comment by xmzzz** [comment]
> The commit is for future packaging deb preparation.
> 
> https://github.com/revyos/thead-kernel/blob/8cf226ab71549e0e07ba8fff38950bd45380b901/scripts/package/builddeb#L150
> 
> `$MAKE -s -f $srctree/Makefile image_name` equal to `KBUILD_IMAGE`
> 
> `KBUILD_IMAGE` determines the kernel copied to the deb package

Thank you for clarification.

If the purpose is to copy the `Image` instead of `Image.gz` during packaging deb, I suggest modifying `scripts/package/builddeb` directly instead of making changes to the `arch/riscv/Makefile`.
Because both `Image` and `Image.gz` are generated by default, that change will prevent `Image.gz` from being generated and make the makefile code logic unclear.

If this is a temporary solution, it is also recommended to add code comments and commit messages, which will be helpful for future code maintenance.

I may not have considered it comprehensively. Thank you for correcting it :)

**Comment by RevySR** [comment]
> Thank you for clarification.
> 
> If the purpose is to copy the `Image` instead of `Image.gz` during packaging deb, I suggest modifying `scripts/package/builddeb` directly instead of making changes to the `arch/riscv/Makefile`. Because both `Image` and `Image.gz` are generated by default, that change will prevent `Image.gz` from being generated and make the makefile code logic unclear.
> 
> If this is a temporary solution, it is also recommended to add code comments and commit messages, which will be helpful for future code maintenance.
> 
> I may not have considered it comprehensively. Thank you for correcting it :)

thead-uboot can't start a compressed kernel, it has a bug at now.

It doesn't make sense to provide a compression kernel until this bug is resolved.

**Review by xmzzz — APPROVED** [review]

**Review by nekorouter — APPROVED** [review]
LGTM

**Pull request merged**
