### PR TITLE
revyos_defconfig: enable BRCMFMAC_SDIO

### PR DESCRIPTION
**Pull request by MilkvHaaland**

### CODE REVIEW

**Comment by nekorouter** [comment]
Is this the only one config to enable BRCMFMAC_SDIO?
`CONFIG_BRCMFMAC=m`

**Comment by MilkvHaaland** [comment]
> Is this the only one config to enable BRCMFMAC_SDIO? `CONFIG_BRCMFMAC=m`

Yes. Only need this one, CONFIG_BRCMFMAC=m

The new revyos_defconfig is generated by the following steps.

```
make ARCH=riscv
make revyos_defconfig
make menuconfig
```

Select CONFIG_BRCMFMAC

```
make savedefconfig
make defconfig arch/riscv/configs/revyos_defconfig
```

**Comment by nekorouter** [comment]
tested by nekorouter.

@MilkvHaaland Do AIC8800 support will not compatible with this config? It has to be disabled?

**Comment by MilkvHaaland** [comment]
> tested by nekorouter.
> 
> @MilkvHaaland Do AIC8800 support will not compatible with this config? It has to be disabled?

AIC8800 and BRCMFMAC can be built at the same time. I didn't disable AIC8800.

**Comment by RevySR** [comment]
https://github.com/revyos/thead-kernel/commit/6bafa84231401b6ff9098c3aa3201397788c8fc9

merged

**Pull request closed without merging**
